# Generated by Django 4.2.26 on 2025-11-14 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nhi_number', models.CharField(help_text='National Health Index number', max_length=7, unique=True)),
                ('datetime_of_arrival', models.DateTimeField()),
                ('presenting_complaint', models.TextField()),
                ('past_medical_history', models.TextField(blank=True)),
                ('current_parent_specialty', models.CharField(choices=[('ED', 'Emergency Department'), ('MEDICINE', 'Medicine'), ('SURGERY', 'Surgery'), ('ORTHOPAEDICS', 'Orthopaedics')], max_length=20)),
                ('current_responsible_team', models.CharField(choices=[('ED', 'Emergency Department'), ('MEDA', 'Medical Team A'), ('MEDB', 'Medical Team B'), ('SURGA', 'Surgical Team A'), ('SURGB', 'Surgical Team B'), ('ORTHO', 'Orthopaedics')], max_length=10)),
                ('referral_source', models.CharField(choices=[('ED', 'Emergency Department'), ('CLINIC', 'Clinic'), ('GP', 'General Practitioner')], max_length=10)),
                ('referral_time', models.DateTimeField()),
                ('clerking_status', models.CharField(choices=[('AWAITING', 'Awaiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=15)),
                ('clerking_doctor', models.CharField(blank=True, max_length=200)),
                ('clerking_completed_at', models.DateTimeField(blank=True, null=True)),
                ('post_take_ward_round_status', models.CharField(choices=[('AWAITING', 'Awaiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=15)),
                ('ptwr_doctor', models.CharField(blank=True, max_length=200)),
                ('ptwr_completed_at', models.DateTimeField(blank=True, null=True)),
                ('admission_type', models.CharField(choices=[('ACUTE', 'Acute'), ('ELECTIVE', 'Elective')], default='ACUTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-datetime_of_arrival'],
            },
        ),
        migrations.CreateModel(
            name='WardRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_round_type', models.CharField(choices=[('POST_TAKE', 'Post Take Ward Round'), ('GENERAL', 'General Ward Round')], max_length=15)),
                ('doctor', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_rounds', to='patients.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('MEDICINE', 'Medicine'), ('SURGERY', 'Surgery'), ('ORTHOPAEDICS', 'Orthopaedics'), ('RENAL', 'Renal'), ('OPHTHALMOLOGY', 'Ophthalmology')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='REQUESTED', max_length=15)),
                ('requested_by', models.CharField(max_length=200)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_requests', to='patients.patient')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
