# Generated by Django 4.2.26 on 2025-11-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="bed_number",
            field=models.IntegerField(
                blank=True, help_text="Bed number (1-16)", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="location",
            field=models.CharField(
                choices=[
                    ("ED", "Emergency Department"),
                    ("WARD1", "Ward 1"),
                    ("WARD2", "Ward 2"),
                    ("WARD3", "Ward 3"),
                    ("WARD4", "Ward 4"),
                    ("WARD5", "Ward 5"),
                ],
                default="ED",
                max_length=10,
            ),
        ),
    ]
