# Generated by Django 4.2.26 on 2025-11-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_bed_number_patient_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="admission_complete",
            field=models.BooleanField(
                default=False,
                help_text="Has the acute admission process been completed?",
            ),
        ),
    ]
