# Generated by Django 4.2.26 on 2025-11-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patient_admission_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="admission_complete",
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_category",
            field=models.CharField(
                choices=[
                    ("ED", "ED Patient"),
                    ("ACUTE_INPROCESS", "Acute - In Process"),
                    ("ACUTE_ADMITTED", "Acute - Admitted"),
                    ("ELECTIVE", "Elective"),
                ],
                default="ED",
                help_text="Current patient category in workflow",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="priority_flag",
            field=models.BooleanField(default=False, help_text="High priority patient"),
        ),
        migrations.AddField(
            model_name="patient",
            name="referral_reason",
            field=models.TextField(
                blank=True, help_text="Reason for referral to specialty"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="referral_to_specialty_datetime",
            field=models.DateTimeField(
                blank=True, help_text="When referred from ED to specialty", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="weekend_review",
            field=models.BooleanField(
                default=False, help_text="Flagged for weekend review"
            ),
        ),
    ]
