# Generated by Django 4.2.26 on 2025-11-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_remove_patient_admission_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultrequest",
            name="comments",
            field=models.TextField(blank=True, help_text="Reviewer comments"),
        ),
        migrations.AddField(
            model_name="patient",
            name="issues",
            field=models.TextField(blank=True, help_text="Current issues and problems"),
        ),
        migrations.AddField(
            model_name="patient",
            name="summary",
            field=models.TextField(blank=True, help_text="Clinical summary"),
        ),
    ]
